# version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: sqldb-1
    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: sqld_db
      POSTGRES_USER: sqld_user
      POSTGRES_PASSWORD: sqld_pass
      TZ: Asia/Seoul

    volumes:
      # DB 데이터 영구 저장 (로컬/서버 디렉토리)
      - ./data:/var/lib/postgresql/data

      # 초기 SQL (선택)
      - ./init:/docker-entrypoint-initdb.d:ro

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sqld_user -d sqld_db"]
      interval: 10s
      timeout: 5s
      retries: 5

# 이 컨테이너 생성 명령어 실행 전에 반드시 도커 데스크탑이 먼저 실행되고 있어야 합니다.
# docker-compose로 실행바랍니다. (참고로 docker compose가 최신 버전입니다.) 
# docker-compose -p <프로젝트명> -f <파일명> up -d, mariadb.yaml -> 기본 파일인 docker-compose.yml 대신 사용
# 컨테이너 실행 : docker-compose -p postgres_db -f postgresql.yml up -d

# 한번이라도 컨테이너 초기화 생성되었는데, 다시 컨테이너를 올리는 경우라면 기존 컨테이너를 내리고 초기화 필요
# docker-compose -p postgres_db -f postgresql.yml down
# rm -rf ./data/*

# 또한 반대로 백업을 목적으로 data 볼륨을 복사했다가 다시 postgresql을 컨테이너로 올려서 복원하는 경우에는, 컨테이너를 생성시키기 전에 미리 data 볼륨에 기존 백업해 두었던 파일들을 복사해 둔 상태에서 다음을 실행하기 (참고로 백업 시에는 postgresql을 내리고 백업해야 하고, postgresql는 메이저 버전을 반드시 맞추어야 함. 단 리눅스는 계열만 맞으면 무관)

# docker-compose -p postgres_db -f postgresql.yml up -d